project:
  type: website

website:
  title: ""

  sidebar:
    tools:
      - icon: github
        href: https://github.com/td-bn
    style: docked
    search: true
    contents: 
      - section: Programming
        contents: rust
      - section: Decentralization
        contents: 
          - section: tbDEX and SSI
            contents: decentralization/tbd/*
          - section: Bitcoin
            contents: decentralization/btc/*
      - section: ML/AI
        contents: fastai/*

  page-footer:  "This website that is build using [Quarto](https://quarto.org/docs/websites)."
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
