project:
  type: website

website:
  title: ""

  sidebar:
    tools:
      - icon: github
        href: https://github.com/td-bn
    style: docked
    search: true
    contents: auto

  page-footer:  "This website that is build using [Quarto](https://quarto.org/docs/websites)."
      
format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
